version: "3.7"
services:
  core:
    container_name: core
    build: core/.
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      API_PREFIX: ${API_PREFIX:-/api}
      DOMAIN: ${DOMAIN:-127.0.0.1}
    restart: always
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.core.rule=Host(`${DOMAIN:-192.168.1.106}`) && PathPrefix(`${API_PREFIX:-/api}`)"
      - "traefik.http.middlewares.core-middleware.stripprefix.prefixes=${API_PREFIX:-/api}"
      - "traefik.http.middlewares.core-middleware.stripprefix.forceslash=true"
      - "traefik.http.routers.core.middlewares=core-middleware"
      - "traefik.http.routers.core.entrypoints=web"
      - "traefik.http.services.core.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - database
    volumes:
      - /etc/localtime:/etc/localtime:ro
  ui:
    container_name: ui
    build: terrariumUI/.
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui-http.rule=Host(`${DOMAIN:-192.168.1.106}`)"
      - "traefik.http.middlewares.ui-http-redirectscheme.redirectscheme.scheme=http"
      - "traefik.http.middlewares.ui-http-redirectscheme.redirectscheme.permanent=true"
      - "traefik.http.routers.ui-http.middlewares=ui-http-redirectscheme"
      - "traefik.http.routers.ui-http.entrypoints=web"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - database
    depends_on:
      - core
  db:
    container_name: db
    image: hypriot/rpi-mysql 
    environment:
      MYSQL_DATABASE: 'terra'
      MYSQL_ROOT_PASSWORD: 'root'
      DB_PATH_HOST: ./volumes/db
    volumes:
      - ./volumes/db:/var/lib/mysql:rw,delegated
    ports:
      - "3306:3306"
    restart: always
    networks:
      - database
networks:
  traefik:
    external:
      name: traefik
  database:
      name: database
